Project for Statistical Learning course. 

Data set: Laliga.csv

Github Link:  https://classroom.github.com/a/RP5QgBy2 

Think of yourself, currently working as a Business analyst in one of the top sports company. The senior management team has asked you to come up with metrics with which they can gauge which team will win the upcoming La Liga cup (Football tournament).

The data set contains information on all the teams so far participated in all the past tournaments. It has data about how many goals each team scored, conceded, how many times they came within first 6 positions, how many seasons they have qualified, their best position in the past etc.

 

You are required to do the following:

Read the data set and replace dashes with 0 to make sure you can perform arithmetic operations on the data. (2.5 points)
Print all the teams which have started playing between 1930-1980. (5 points)
Print the list of teams which came Top 5 in terms of points (2.5 points)
Write a function with name “Goal_diff_count” which should return all the teams with their Goal Differences. Using the same function, find the team which has maximum and minimum goal difference. (5 points)
Goal_diff_count = GoalsFor - GoalsAgainst

Create a new column with name “Winning Percent” and append it to the data set (5 points)
Percentage of Winning = (GamesWon / GamesPlayed)*100

If there are any numerical error, replace it with 0%

Print the top 5 teams which has the highest Winning percentage

Group teams based on their “Best position” and print the sum of their points for all positions (5 points)
Eg: Best Position     Points

         1                   25000

         2                    7000

---------------------------------------------------------------------------------------------------------------------
<font size="5">Read the data set and replace dashes with 0 to make sure you can perform arithmetic operations on the data. 
(2.5 points)</font>

In [87]:
import pandas as pd
#Reading CSV and skipping row 0, now the dataframe has correct column names
df = pd.read_csv("Laliga.csv", skiprows=[0])
#Replacing '-' with 0
df.replace('-', 0, inplace=True)

In [88]:
df.head()

,Pos,Team,Seasons,Points,GamesPlayed,GamesWon,GamesDrawn,GamesLost,GoalsFor,GoalsAgainst,Champion,Runner-up,Third,Fourth,Fifth,Sixth,T,Debut,Since/LastApp,BestPosition
0,1,Real Madrid,86,4385,2762,1647,552,563,5947,3140,33,23,8,8,3,4,79,1929,1929,1
1,2,Barcelona,86,4262,2762,1581,573,608,5900,3114,25,25,12,12,4,6,83,1929,1929,1
2,3,Atletico Madrid,80,3442,2614,1241,598,775,4534,3309,10,8,16,9,7,6,56,1929,2002-03,1
3,4,Valencia,82,3386,2664,1187,616,861,4398,3469,6,6,10,11,10,7,50,1931-32,1987-88,1
4,5,Athletic Bilbao,86,3368,2762,1209,633,920,4631,3700,8,7,10,5,8,10,49,1929,1929,1

---------------------------------------------------------------------------------------------------------------------
<font size="5">Print all the teams which have started playing between 1930-1980 (5 points)</font>

In [89]:
#Debut column contains some Year in the format 2019 and some other in format 2019-20.
#Using split function to split at '-' and then keeping only the first part of the split
df['Debut'] = df['Debut'].str.split('-').str[0]
#Convert Debut columns from 'object' datatype to 'int64' for arithematic operation
df.Debut = df.Debut.astype('int64')

In [90]:
#Conditional selecting of rows where Debut is from 1930 to 1980 inclusive. Assign a new dataframe
df_strtplay = df[(df['Debut'] >= 1930) & (df['Debut'] <=1980)]
#Print the team values
print(df_strtplay['Team'])

3                Valencia
5                 Sevilla
8                Zaragoza
9              Real Betis
10    Deportivo La Coruna
11             Celta Vigo
12             Valladolid
14         Sporting Gijon
15                Osasuna
16                 Malaga
17                 Oviedo
18               Mallorca
19             Las Palmas
21                Granada
22         Rayo Vallecano
23                  Elche
25               Hercules
26               Tenerife
27                 Murcia
28                 Alaves
29                Levante
30              Salamanca
31               Sabadell
32                  Cadiz
34              Castellon
37                Cordoba
39             Recreativo
40              Burgos CF
41             Pontevedra
46              Gimnastic
49               Alcoyano
50                   Jaen
52             AD Almeria
54                 Lleida
57                 Condal
58        Atletico Tetuan
59       Cultural Leonesa
Name: Team, dtype: object

---------------------------------------------------------------------------------------------------------------------
<font size="5">Print the list of teams which came Top 5 in terms of points (2.5 points)</font>

In [91]:
#Convert Points columns from 'object' datatype to 'int64' for arithematic operation
df.Points = df.Points.astype('int64')

In [92]:
# Using nlargest function available in pandas 0.17.0b version. Assign it to new dataframe
df_toppoints = df.nlargest(5, 'Points')
# Print the team names and points of dataframe
print(df_toppoints[['Team','Points']])

              Team  Points
0      Real Madrid    4385
1        Barcelona    4262
2  Atletico Madrid    3442
3         Valencia    3386
4  Athletic Bilbao    3368

In [93]:
# Alternate way to do this
print(df.sort_values('Points', ascending=False).head()[['Team','Points']])

              Team  Points
0      Real Madrid    4385
1        Barcelona    4262
2  Atletico Madrid    3442
3         Valencia    3386
4  Athletic Bilbao    3368

---------------------------------------------------------------------------------------------------------------------
<font size="5">Write a function with name “Goal_diff_count” which should return all the teams with their Goal Differences. Using the same function, find the team which has maximum and minimum goal difference. (5 points)
Goal_diff_count = GoalsFor - GoalsAgainst</font>

In [94]:
df.head(2)
#Converting GoalsFor column to int64 datatype
df.GoalsFor = df.GoalsFor.astype('int64')

#Converting GoalsAgainst column to int64 datatype
df.GoalsAgainst = df.GoalsAgainst.astype('int64')

In [95]:
#Function returning a pandas series with Team names and their Goal Differences
Goal_diff_count = lambda x:pd.Series([x.Team, x.GoalsFor - x.GoalsAgainst], index=['Team', 'GoalDiff'])

#Applying the function to the data frame and printing it
print(df.apply(Goal_diff_count, axis=1, result_type='expand'))

#Using the same function to and finding team with Maximum Goal Difference
print('Team with maximum goal difference\n',df.apply(Goal_diff_count, axis=1, result_type='expand').max())

#Using the same function to and finding team with Minimum Goal Difference
print('Team with minimum goal difference\n',df.apply(Goal_diff_count, axis=1, result_type='expand').min())

                   Team  GoalDiff
0           Real Madrid      2807
1             Barcelona      2786
2       Atletico Madrid      1225
3              Valencia       929
4       Athletic Bilbao       931
5               Sevilla       307
6              Espanyol      -280
7         Real Sociedad        -2
8              Zaragoza      -164
9            Real Betis      -333
10  Deportivo La Coruna      -136
11           Celta Vigo      -346
12           Valladolid      -413
13     Racing Santander      -525
14       Sporting Gijon      -399
15              Osasuna      -334
16               Malaga      -342
17               Oviedo      -309
18             Mallorca      -189
19           Las Palmas      -399
20           Villarreal       103
21              Granada      -338
22       Rayo Vallecano      -328
23                Elche      -272
24               Getafe      -113
25             Hercules      -334
26             Tenerife      -125
27               Murcia      -385
28               Alaves      -165
29              Levante      -202
..                  ...       ...
31             Sabadell      -228
32                Cadiz      -269
33             Logrones      -198
34            Castellon      -169
35             Albacete       -90
36              Almeria      -122
37              Cordoba      -145
38           Compostela       -42
39           Recreativo       -94
40            Burgos CF       -94
41           Pontevedra       -56
42             Numancia       -98
43                Eibar       -28
44               Arenas       -81
45          Real Burgos       -38
46            Gimnastic      -114
47          Extremadura       -55
48               Merida       -45
49             Alcoyano      -107
50                 Jaen       -62
51           Real Union       -31
52           AD Almeria       -45
53               Europa       -34
54               Lleida      -112
55              Leganes       -19
56                Xerez       -28
57               Condal       -20
58      Atletico Tetuan       -34
59     Cultural Leonesa       -31
60               Girona         0

[61 rows x 2 columns]
Team with maximum goal difference
 Team        Zaragoza
GoalDiff        2807
dtype: object
Team with minimum goal difference
 Team        AD Almeria
GoalDiff          -525
dtype: object

<font size="5">Create a new column with name “Winning Percent” and append it to the data set (5 points) Percentage of Winning = (GamesWon / GamesPlayed)*100

If there are any numerical error, replace it with 0%

Print the top 5 teams which has the highest Winning percentage</font>

In [96]:
#Converting GoalsAgainst column to int64 datatype
df.GamesWon = df.GamesWon.astype('int64')

#Converting GoalsAgainst column to int64 datatype
df.GamesPlayed = df.GamesPlayed.astype('int64')

df.head(2)

,Pos,Team,Seasons,Points,GamesPlayed,GamesWon,GamesDrawn,GamesLost,GoalsFor,GoalsAgainst,Champion,Runner-up,Third,Fourth,Fifth,Sixth,T,Debut,Since/LastApp,BestPosition
0,1,Real Madrid,86,4385,2762,1647,552,563,5947,3140,33,23,8,8,3,4,79,1929,1929,1
1,2,Barcelona,86,4262,2762,1581,573,608,5900,3114,25,25,12,12,4,6,83,1929,1929,1

In [97]:
#Creating new column with winning percentage and adding it to dataframe.
#No numerical error as both Games won and Games played were converted to int64
df['Winning Percent'] = (df['GamesWon'] / df['GamesPlayed'])*100

#Printing top 5 teams which have the highest winning percentage
print(df.nlargest(5, 'Points')[['Team','Winning Percent']])

              Team  Winning Percent
0      Real Madrid        59.630702
1        Barcelona        57.241130
2  Atletico Madrid        47.475134
3         Valencia        44.557057
4  Athletic Bilbao        43.772629

<font size="5">Group teams based on their “Best position” and print the sum of their points for all positions (5 points) Eg: Best Position Points

     1                   25000

     2                    7000

In [98]:
#Grouping based on BestPosition and summing their points for all positions and printing output
print(df.groupby(['BestPosition']).sum()[['Points']])

              Points
BestPosition
1              27933
2               6904
3               5221
4               6563
5               1884
6               2113
7               1186
8               1134
9                 96
10               450
11               445
12               511
14                71
15                14
16                81
17               266
19                81
20                34